- name: Install application site
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/{{ cookiecutter.project_slug }}.conf
  notify: Restart NGINX

- name: Create NGINX symbolic link for main site
  file:
    src: /etc/nginx/sites-available/{{ cookiecutter.project_slug }}.conf
    dest: /etc/nginx/sites-enabled/{{ cookiecutter.project_slug }}.conf
    state: link
  notify: Restart NGINX
